---
output:
  pdf_document:
    keep_tex: true
---
```{r}

```

```{r}
# Load the necessary library
library(here)
library(dplyr)
library(reshape2)
library(ggplot2)
library(patchwork)
library(tidyr)
```


```{r}
# Read the dataset
data <- read.csv(here("CA\\CA1\\CA1.csv"))
str(data)
```


```{r}
#Qtn 1 
# Compute the sample mean vectors for each time period
mean_vectors <- data %>%
  group_by(TimePeriod) %>%
  summarise(
    MaxBreadth = mean(MaxBreadth, na.rm = TRUE),
    BasHeight = mean(BasHeight, na.rm = TRUE),
    BasLength = mean(BasLength, na.rm = TRUE),
    NasHeight = mean(NasHeight, na.rm = TRUE)
  )

mean_vectors
```


```{r}
# #Qtn 2 function
# # Function to generate a heat map for a given time period
# generate_heat_map <- function(time_period) {
#   filtered_data <- data[data$TimePeriod == time_period,]
#   cor_matrix <- cor(filtered_data[,1:4]) # Assuming the first four columns are the variables
# 
#   # Melt the correlation matrix for ggplot
#   melted_cor_matrix <- melt(cor_matrix)
# 
#   # Plot
#   ggplot(melted_cor_matrix, aes(x = Var1, y = Var2, fill = value)) +
#     geom_tile() +
#     geom_text(aes(label = sprintf("%.2f", value)), color = "black", size = 3) +
#     #scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
#    #                      midpoint = 0, limit = c(-1,1), space = "Lab", 
#    #                      name="Pearson\nCorrelation") +
#     theme_minimal() +
#     theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 9, hjust = 1, family = "Arial"),
#           axis.text.y = element_text(size = 9, family = "Arial"),
#           plot.title = element_text(size = 14, family = "Arial")) +
#     labs(x = '', y = '', title = paste("Correlation Matrix Heat Map \n for Time Period", time_period))
# }

```


```{r}
# #Q2 cntd
# # Generate heat map for time periods
# time_periods <- unique(data$TimePeriod)
# plot_list <- list()
# 
# for (time_period in time_periods) {
#   plot_list[[time_period]] <- generate_heat_map(time_period)
# }
# 
# # Combine the plots. Adjust the layout with `plot_layout()`
# combined_plot <- wrap_plots(plot_list, ncol = 3) + 
#   plot_layout(guides = 'collect')
# 
# #save plots
# #ggsave("correlation_heatmaps.png", plot = combined_plot, width = 10, height = 6, units = "in")
# 
# combined_plot
```

```{r}
# Q3

# Filter data for period 1
data_period_1 <- data[data$TimePeriod == 1,]

# Extract vectors for X1 and X3
x1 <- data_period_1$MaxBreadth
x3 <- data_period_1$BasLength

# Compute deviation vectors from their means
x1_dev <- x1 - mean(x1)
x3_dev <- x3 - mean(x3)

# Calculate the cosine of the angle using the dot product
cos_angle <- sum(x1_dev * x3_dev) / (sqrt(sum(x1_dev^2)) * sqrt(sum(x3_dev^2)))
cos_angle
# Calculate the angle in radians
angle_radians <- acos(cos_angle)

# Convert the angle to degrees
angle_degrees <- angle_radians * (180 / pi)

angle_degrees
```
```{r}
#Qtn 3 Bonus Qtn
period1_obs2 <- data_period_1[1:2,]

x1_dev <- period1_obs2$MaxBreadth - mean(period1_obs2$MaxBreadth)
x2_dev <- period1_obs2$BasHeight - mean(period1_obs2$BasHeight)
x3_dev <- period1_obs2$BasLength - mean(period1_obs2$BasLength)
x4_dev <- period1_obs2$NasHeight - mean(period1_obs2$NasHeight)

dev_vectors <- rbind(c(x1_dev), c(x2_dev), c(x3_dev), c(x4_dev))
dev_vectors

dev_vectors_df <- data.frame(
        "x" = dev_vectors[,1],
        'y' = dev_vectors[,2],
        'vector' = c('d1', 'd2', 'd3', 'd4'))
dev_vectors_df


```


```{r}
#Qtn 3 Bonus Qtn ctnd
# Plot vectors
ggplot(dev_vectors_df, aes(xend = x, yend = y)) +
  geom_segment(aes(x = 1, y = 1, xend = x, yend = y), 
               arrow = arrow(type = "closed", length = unit(0.1, "inches")),
               color = "blue",
               linetype = "dotted") +
  geom_text(aes(x = x, y = y, label = vector), nudge_x = 0.2, nudge_y = 0.2, color = "red") +
  coord_fixed() + 
  theme_minimal() +
  labs(title = "Deviation Vectors", x = "X Axis", y = "Y Axis")


```



```{r}
#Qtn 4
b <- c(-1,0,0,3)
means_matrix <- as.matrix(mean_vectors[, 2:ncol(mean_vectors)])
y_means <- means_matrix%*%b
#means for y1 to y5
y_means

#now calculating the covariance matrix
data = data %>% mutate(Y = 3*NasHeight - MaxBreadth) #the y value for each data data point
y_data <- data %>% select(TimePeriod, Y)

#create an index to match data points ie 30 data points for 5 periods
index <- rep(seq(1,30), times = 5)
y_data$index <- index
y_data_wide <- pivot_wider(y_data, names_from = TimePeriod, values_from = Y) #pivot data to use cov function

head(y_data_wide)
y_data_wide <- y_data_wide %>% select(-index) #remove the index from cov calculation
y_covariances <- cov(y_data_wide)
y_covariances
```


